### ISSUE TITLE
Update characters from battle.net

### ISSUE THREAD

**Issue by utecht** [spacegoatsc2c/ngoat#3]
Theoretically battle.net will start regularly updating character data soon.  The API won't change so we can go ahead and start listening and making sure our database is updated.

**Comment by utecht** [comment]
I guess this issue should technically be on the other repository, but I think it is better if all issues are in one place, and this one will have more problems and change more so it is probably safer to keep everything here.

**Comment by utecht** [comment]
My version has been pushed, merge it into your and wrap it around the command.

**Comment by quasarj** [comment]
Resolved by https://github.com/spacegoatsc2c/goat-at-rest/commit/6a9637ea0ad44a7d8f58727f08ff954d9edd28c0
