### ISSUE TITLE
Finish boss/character-home template

### ISSUE THREAD

**Issue by utecht** [spacegoatsc2c/ngoat#7]
Should probably just implement the feed.component after filtering for a users articles.

This will also need REST endpoints to be created for both.

**Comment by quasarj** [comment]
Can you explain it in words a bit better?

**Comment by utecht** [comment]
Need an endpoint that will return articles filtered to return articles for a single character or boss.

e.g.

url?boss=2 

Maybe django-rest has something built in.

**Comment by quasarj** [comment]
Fixed in https://github.com/spacegoatsc2c/goat-at-rest/commit/48225a681a50e41649e1b5d289d5b2ce97dd3141 

The syntax is as follows:

api/articles/?character__id=3
api/articles/?boss__id=5

**Comment by utecht** [comment]
Still need to actually implement this in the angular.
